// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrdAZMbU9x_fnpJlxGGPEwB-YHsvE_c50',
    appId: '1:1046588524439:web:1fed9c85094e96d85c26d2',
    messagingSenderId: '1046588524439',
    projectId: 'nets-48e4e',
    authDomain: 'nets-48e4e.firebaseapp.com',
    storageBucket: 'nets-48e4e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWyZPc8n6FwYdzX1jn9NMQe1xdTlF6Zus',
    appId: '1:1046588524439:android:b773632d6608fed35c26d2',
    messagingSenderId: '1046588524439',
    projectId: 'nets-48e4e',
    storageBucket: 'nets-48e4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA123dTn-TtWfF80L1G8XXbavFFjrY8qRA',
    appId: '1:1046588524439:ios:9d632172a0e11ead5c26d2',
    messagingSenderId: '1046588524439',
    projectId: 'nets-48e4e',
    storageBucket: 'nets-48e4e.appspot.com',
    iosClientId: '1046588524439-enh2736r1q7vn54mifvidsl0bs6apo3s.apps.googleusercontent.com',
    iosBundleId: 'com.griitingz.3nets',
  );
}
